### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by kocherzhenko**

### CODE REVIEW

**Comment by ankushbhagat124** [comment]
Hey Kocherzhenko!
This Quantum Gates implementation project of yours was just amazing.
I am facing some issues running the code into my Windows system.

Can we connect via gmail or something so that you can help me with the above issue?

**Comment by kocherzhenko** [comment]
Sure, we can try (although I never tested it on Windows). Let me know what
times work for you. I am on Pacific time and weekends are generally best
for me.

All the best,
Aleksey

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by ankushbhagat124** [comment]
Extremely Sorry for the late reply 😣
Actually I was out of station last weekend.

Alright we can have a meet this Saturday if its fine for you. I am on Indian Standard Time and any time will suit me.
So you can tell me the time suitable to you and then we can just keep a short g-meet to discuss on the project and try running it on Windows.

Sincerely,
Ankush Bhagat

**Comment by kocherzhenko** [comment]
Unfortunately, I won't be available on Friday night/Saturday morning
Pacific time: I will be traveling and running a half-marathon. I am free to
meet on Saturday night Pacific/Sunday morning IST, if that works for you.
You can set the specific time. Sunday and Monday (Memorial Day in the US)
would also work.

All the best,
Aleksey

**Comment by ankushbhagat124** [comment]
Yeah no problem, so we can have a meet on Saturday Night (Pacific) / Sunday Morning (IST).
The time will be 10:30pm Sat Night for Pacific if its fine for you.
Meet Title: Quantum Meet
Google Meet joining info
Video call link: https://meet.google.com/vhf-xdvm-rhc

**Comment by kocherzhenko** [comment]
Confirmed!

**Comment by kocherzhenko** [comment]
Hey, Ankush - I tried joining the Google meet using the link you provided
and waited for ~15 min, but, I guess, we missed each other. Happy to
reschedule, if necessary.

All the best,
Aleksey

**Comment by ankushbhagat124** [comment]
Can you come now on the same link?
I just read the pacific time wrong. My apologies...

I will be waiting on the same link for an hour. If you are able to come then that's great otherwise we can keep tmrw same time same link.

Regards, 
Ankush Bhagat

**Pull request merged**
